#!/bin/sh
xrandr \
  --output VIRTUAL1 --off \
  --output eDP1 --primary \
    --mode 1920x1080 \
    --pos 3840x1080 \
  --rotate normal \
  --output DP1 --off \
  --output DP2-1 --off \
  --output DP2-2 \
    --mode 3840x2160 \
    --pos 0x0 \
  --rotate normal \
  --output DP2-3 --off \
  --output HDMI2 --off \
  --output HDMI1 --off \
  --output DP2 --off
