#!/bin/bash

if [ -L ~/mp3s ]; then
  rm ~/mp3s
fi

if [ -d /media/FreeAgent/mp3s ]; then
  ln -s /media/FreeAgent/mp3s ~/mp3s
elif [d /media/PASSPORT/mp3s ]; then
  ln -s /media/PASSPORT/mp3s ~/mp3s
else
  echo "One of your drives needs to be connected"
  exit 0
fi
banshee > /dev/null 2>&1 &
